### ISSUE TITLE
adding convenience operators 

### ISSUE THREAD

**Issue by Janos95** [JamesYang007/FastAD#63]
Hey,
I am trying out your lib and it seems nice. I think it would be nice to have some convenience operators like += etc. Also I was wondering why it is not possible to use both normal floating point values in arithmetic expressions involving ad::Var? I think it would be nice to be able to do something like
`Var<double> a, b{2}; a = 5. * b * b;`

**Comment by JamesYang007** [comment]
Hey, thanks for trying out my library! 

So for reverse AD, we don't actually compute anything until we call `autodiff` on the final expression. When we write for example
```cpp
Var<double> a, b{2};
a = 5. * b * b;
```
the result of `5. * b * b` does not get computed and "stored" in `a`. The expression `a = 5. * b * b` returns a completely different object representing it. So a working example would be something like
```cpp
Var<double> a, b{2};
auto expr = (a = 5. * b * b);
autodiff(expr); // now a and b contain derivative values
```
And I couldn't think of a good use-case where `operator+=` would shine from simply using `operator=`. Is there a use-case you had in mind?

For forward AD using `ad::ForwardVar`, I think it makes sense to overload these operators so I can add that feature.

For allowing floating point values with ad::Var, I think that's a fair point too, I'll get around adding that! For now, you have to use `ad::constant(5.)` in place of `5.`.

**Comment by JamesYang007** [comment]
#84 literals can now be used to construct expressions without the need for user to explicitly write `ad::constant`

**Comment by JamesYang007** [comment]
#86 includes support for convenience operators: `operator+=, operator-=, operator*=., operator/=`
