### ISSUE TITLE
Supporting mat transpose.

### ISSUE THREAD

**Issue by kilasuelika** [JamesYang007/FastAD#97]
`mat` transpose is very common in scientific computing. If we want to support that, can we write a function in `reverse/core/unary.hpp` to directly transpose underneath values and adjoints?

I would like to make a PR but I'm not sure if the above idea is correct.

**Comment by kilasuelika** [comment]
I'm working on a TransposeNode.

**Comment by JamesYang007** [comment]
Good point! How did I miss such an important operator. I agree transpose should be a separate node rather than a specialization of a unary node. I intended unary nodes to represent element-wise operations.
